### ISSUE TITLE
建议不要把暴力抢课功能开源，如果你不希望抢课服务器瘫痪的话

### ISSUE THREAD

**Issue by PairZhu** [shaxiu/njtech_grabber#1]
学校的服务器已经很烂了，这要是被传广了，学校抢课服务器就完了，建议还是这些辅助性的功能，暴力性质的，增大服务器压力的脚本就算了吧

**Comment by shaxiu** [comment]
> 

好的，感谢提醒！

**Comment by shaxiu** [comment]
> 学校的服务器已经很烂了，这要是被传广了，学校抢课服务器就完了，建议还是这些辅助性的功能，暴力性质的，增大服务器压力的脚本就算了吧

好的，感谢提醒！
