### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by xltx88** [shaxiu/njtech_grabber#2]
非常感谢开发者编写这个程序，但是我想问一下捡漏脚本是因为什么原因删除呢？

**Comment by shaxiu** [comment]
> 非常感谢开发者编写这个程序，但是我想问一下捡漏脚本是因为什么原因删除呢？

捡漏脚本可能会增加学校土豆服务器的压力，且如果大面积使用可能会造成不良影响，因此删除。并且由于学校今年开始分批次选课，因此捡漏的几率大大降低，实用性降低了很多。

**Comment by yhj233** [comment]
您好 能私发一下吗，不是校友，我们学校今年也用了方正8，想学习一下

**Comment by yhj233** [comment]
> > 非常感谢开发者编写这个程序，但是我想问一下捡漏脚本是因为什么原因删除呢？
> 
> 捡漏脚本可能会增加学校土豆服务器的压力，且如果大面积使用可能会造成不良影响，因此删除。并且由于学校今年开始分批次选课，因此捡漏的几率大大降低，实用性降低了很多。

您好 能私发一下吗，不是校友，我们学校今年也用了方正8，想学习一下

**Comment by shaxiu** [comment]
> > > 非常感谢开发者编写这个程序，但是我想问一下捡漏脚本是因为什么原因删除呢？
> > 
> > 
> > 捡漏脚本可能会增加学校土豆服务器的压力，且如果大面积使用可能会造成不良影响，因此删除。并且由于学校今年开始分批次选课，因此捡漏的几率大大降低，实用性降低了很多。
> 
> 您好 能私发一下吗，不是校友，我们学校今年也用了方正8，想学习一下

留一下邮箱
